name: Bug Report
description: Report a bug to help us improve metrics-agent.
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        感谢提交问题，请尽量提供可复现信息。

  - type: textarea
    id: summary
    attributes:
      label: Summary / 问题概述
      description: What happened?
      placeholder: Describe the bug clearly.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce / 复现步骤
      description: List reproducible steps.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior / 期望行为
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior / 实际行为
      description: What happened instead?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version / 版本
      description: For example `v1.2.4`
      placeholder: v1.2.4
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment / 环境信息
      description: OS, Docker version, deploy platform, etc.
      placeholder: |
        OS:
        Docker:
        Platform:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / 日志
      description: Paste relevant logs or screenshots.
      render: shell
    validations:
      required: false
